import type { Recipe, BrewLog, Equipment } from '@/types/database'

const now = new Date().toISOString()

export const mockRecipes: Recipe[] = [
  {
    id: 'mock-r1', created_at: now, updated_at: now,
    name: 'West Coast IPA', category: 'beer', style: 'American IPA',
    description: 'Сухой, горький, яркий цитрусовый аромат',
    batch_size_l: 25, efficiency: 75, boil_time_min: 60, notes: null,
    og_target: 1.068, fg_target: 1.012, abv_target: 7.3,
    ibu_target: 65, srm_target: 8, brix_target: 16.5, ph_target: null,
    malts: [], hops: [], yeasts: [], adjuncts: [],
  },
  {
    id: 'mock-r2', created_at: now, updated_at: now,
    name: 'Oatmeal Stout', category: 'beer', style: 'Oatmeal Stout',
    description: 'Бархатный тёмный стаут с овсянкой',
    batch_size_l: 20, efficiency: 73, boil_time_min: 60, notes: null,
    og_target: 1.072, fg_target: 1.018, abv_target: 7.1,
    ibu_target: 32, srm_target: 35, brix_target: 17.5, ph_target: null,
    malts: [], hops: [], yeasts: [], adjuncts: [],
  },
  {
    id: 'mock-r3', created_at: now, updated_at: now,
    name: 'Belgian Tripel', category: 'beer', style: 'Belgian Tripel',
    description: 'Светлый крепкий бельгийский эль',
    batch_size_l: 25, efficiency: 75, boil_time_min: 90, notes: null,
    og_target: 1.082, fg_target: 1.010, abv_target: 9.4,
    ibu_target: 28, srm_target: 5, brix_target: 19.8, ph_target: null,
    malts: [], hops: [], yeasts: [], adjuncts: [],
  },
  {
    id: 'mock-r4', created_at: now, updated_at: now,
    name: 'Pilsner Classic', category: 'beer', style: 'German Pilsner',
    description: 'Чистый освежающий лагер',
    batch_size_l: 30, efficiency: 78, boil_time_min: 90, notes: null,
    og_target: 1.048, fg_target: 1.010, abv_target: 5.0,
    ibu_target: 38, srm_target: 3, brix_target: 11.9, ph_target: null,
    malts: [], hops: [], yeasts: [], adjuncts: [],
  },
  {
    id: 'mock-r5', created_at: now, updated_at: now,
    name: 'New England IPA', category: 'beer', style: 'New England IPA',
    description: 'Мутный, тропический, мягкая горечь',
    batch_size_l: 25, efficiency: 72, boil_time_min: 60, notes: null,
    og_target: 1.070, fg_target: 1.014, abv_target: 7.3,
    ibu_target: 45, srm_target: 5, brix_target: 17.0, ph_target: null,
    malts: [], hops: [], yeasts: [], adjuncts: [],
  },
  {
    id: 'mock-r6', created_at: now, updated_at: now,
    name: 'Weizen', category: 'beer', style: 'Hefeweizen',
    description: 'Пшеничное с банановым эфиром',
    batch_size_l: 20, efficiency: 72, boil_time_min: 60, notes: null,
    og_target: 1.050, fg_target: 1.012, abv_target: 5.0,
    ibu_target: 12, srm_target: 4, brix_target: 12.4, ph_target: null,
    malts: [], hops: [], yeasts: [], adjuncts: [],
  },
]

export const mockBrews: BrewLog[] = [
  {
    id: 'mock-b1', created_at: now, updated_at: now,
    recipe_id: 'mock-r1', recipe_name: 'West Coast IPA', category: 'beer',
    batch_number: '#042', status: 'fermenting',
    brew_date: '2026-04-28', package_date: null,
    batch_size_l: 25, notes: null,
    og_actual: 1.068, fg_actual: null, abv_actual: null,
    efficiency_actual: 74, total_cost: null, cost_per_liter: null,
  },
  {
    id: 'mock-b2', created_at: now, updated_at: now,
    recipe_id: 'mock-r2', recipe_name: 'Oatmeal Stout', category: 'beer',
    batch_number: '#041', status: 'conditioning',
    brew_date: '2026-04-15', package_date: null,
    batch_size_l: 20, notes: null,
    og_actual: 1.072, fg_actual: null, abv_actual: null,
    efficiency_actual: 73, total_cost: null, cost_per_liter: null,
  },
  {
    id: 'mock-b3', created_at: now, updated_at: now,
    recipe_id: 'mock-r3', recipe_name: 'Belgian Tripel', category: 'beer',
    batch_number: '#040', status: 'ready',
    brew_date: '2026-04-01', package_date: '2026-04-25',
    batch_size_l: 25, notes: null,
    og_actual: 1.082, fg_actual: 1.010, abv_actual: 9.4,
    efficiency_actual: 76, total_cost: null, cost_per_liter: null,
  },
  {
    id: 'mock-b4', created_at: now, updated_at: now,
    recipe_id: 'mock-r4', recipe_name: 'Pilsner Classic', category: 'beer',
    batch_number: '#039', status: 'planned',
    brew_date: '2026-05-12', package_date: null,
    batch_size_l: 30, notes: null,
    og_actual: null, fg_actual: null, abv_actual: null,
    efficiency_actual: null, total_cost: null, cost_per_liter: null,
  },
  {
    id: 'mock-b5', created_at: now, updated_at: now,
    recipe_id: null, recipe_name: 'Манго Комбуча', category: 'kombucha',
    batch_number: '#K01', status: 'fermenting',
    brew_date: '2026-05-01', package_date: null,
    batch_size_l: 10, notes: null,
    og_actual: 1.030, fg_actual: null, abv_actual: null,
    efficiency_actual: null, total_cost: null, cost_per_liter: null,
  },
  {
    id: 'mock-b6', created_at: now, updated_at: now,
    recipe_id: null, recipe_name: 'Лимонад Citrus', category: 'lemonade',
    batch_number: '#L01', status: 'ready',
    brew_date: '2026-04-20', package_date: '2026-04-22',
    batch_size_l: 15, notes: null,
    og_actual: null, fg_actual: null, abv_actual: null,
    efficiency_actual: null, total_cost: null, cost_per_liter: null,
  },
]

export const mockEquipment: Equipment[] = [
  { id: 'mock-e1', created_at: now, updated_at: now,
    name: 'Затирочный чан 50 л', type: 'mash_tun', capacity_l: 50,
    status: 'clean', current_brew_id: null, position_x: 1, position_y: 1, notes: null },
  { id: 'mock-e2', created_at: now, updated_at: now,
    name: 'Сусловарочный котёл 60 л', type: 'brew_kettle', capacity_l: 60,
    status: 'clean', current_brew_id: null, position_x: 3, position_y: 1, notes: null },
  { id: 'mock-e3', created_at: now, updated_at: now,
    name: 'HLT 60 л', type: 'hlt', capacity_l: 60,
    status: 'clean', current_brew_id: null, position_x: 5, position_y: 1, notes: null },
  { id: 'mock-e4', created_at: now, updated_at: now,
    name: 'Ферментер #1', type: 'fermenter', capacity_l: 30,
    status: 'in_use', current_brew_id: 'mock-b1', position_x: 1, position_y: 4, notes: 'West Coast IPA #042' },
  { id: 'mock-e5', created_at: now, updated_at: now,
    name: 'Ферментер #2', type: 'fermenter', capacity_l: 30,
    status: 'in_use', current_brew_id: 'mock-b2', position_x: 3, position_y: 4, notes: 'Oatmeal Stout #041' },
  { id: 'mock-e6', created_at: now, updated_at: now,
    name: 'Ферментер #3', type: 'fermenter', capacity_l: 30,
    status: 'cleaning', current_brew_id: null, position_x: 5, position_y: 4, notes: null },
  { id: 'mock-e7', created_at: now, updated_at: now,
    name: 'Танк дображивания 30 л', type: 'conditioning_tank', capacity_l: 30,
    status: 'in_use', current_brew_id: 'mock-b3', position_x: 7, position_y: 4, notes: 'Belgian Tripel #040' },
  { id: 'mock-e8', created_at: now, updated_at: now,
    name: 'Форфас 50 л', type: 'bright_tank', capacity_l: 50,
    status: 'clean', current_brew_id: null, position_x: 9, position_y: 4, notes: null },
  { id: 'mock-e9', created_at: now, updated_at: now,
    name: 'Кега A', type: 'keg', capacity_l: 30,
    status: 'clean', current_brew_id: null, position_x: 1, position_y: 7, notes: null },
  { id: 'mock-e10', created_at: now, updated_at: now,
    name: 'Кега B', type: 'keg', capacity_l: 30,
    status: 'in_use', current_brew_id: 'mock-b3', position_x: 2, position_y: 7, notes: 'Belgian Tripel' },
  { id: 'mock-e11', created_at: now, updated_at: now,
    name: 'Кега C', type: 'keg', capacity_l: 30,
    status: 'dirty', current_brew_id: null, position_x: 3, position_y: 7, notes: null },
  { id: 'mock-e12', created_at: now, updated_at: now,
    name: 'Чиллер противоточный', type: 'chiller', capacity_l: null,
    status: 'clean', current_brew_id: null, position_x: 7, position_y: 1, notes: null },
  { id: 'mock-e13', created_at: now, updated_at: now,
    name: 'Насос Riptide', type: 'pump', capacity_l: null,
    status: 'clean', current_brew_id: null, position_x: 9, position_y: 1, notes: null },
  { id: 'mock-e14', created_at: now, updated_at: now,
    name: 'Баллон CO₂ 5 кг', type: 'co2_tank', capacity_l: null,
    status: 'in_use', current_brew_id: null, position_x: 11, position_y: 1, notes: '60% заполнен' },
]
